import { ArrowRight, CheckCircle2, FileSearch, Layers3, ShieldCheck, Timer, Upload, WalletCards } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Card } from '../components/ui/Card'
import { Badge } from '../components/ui/Badge'

export const HomePage = () => <>
  <section className="border-b border-slate-200 bg-white"><div className="container-shell grid gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24"><div><Badge tone="info">Für KMU und operative Betriebe</Badge><h1 className="mt-5 max-w-3xl text-4xl font-semibold tracking-tight text-ink sm:text-5xl">Ausschreibungen prüfen. <span className="text-brand-700">Sicher entscheiden.</span> Angebote vorbereiten.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">TenderWerk Copilot strukturiert Vergabeunterlagen, zeigt Fristen und Nachweise mit Fundstellen, gleicht Anforderungen mit Ihrem Firmenprofil ab und führt bis zur internen Freigabe. Die finale Abgabe bleibt bewusst in Ihrer Hand.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/registrieren" className="btn-primary">Demoprojekt testen <ArrowRight className="h-4 w-4"/></Link><Link to="/funktionen" className="btn-secondary">Funktionsumfang ansehen</Link></div><p className="mt-7 text-sm text-slate-500">2024 wurden in Deutschland 199.334 Vergaben mit einem Auftragsvolumen von 135,2 Mrd. € erfasst. Quelle: Statistisches Bundesamt, Vergabestatistik 2024.</p></div><div className="card bg-slate-50 p-4 sm:p-6"><div className="rounded-xl bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-semibold">Unterhaltsreinigung Verwaltungszentrum</p><Badge tone="warning">Go nach Prüfung</Badge></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Insight label="Abgabefrist" value="in 12 Tagen" tone="warning"/><Insight label="Belegabdeckung" value="12 / 15" tone="success"/><Insight label="Muss-Nachweise offen" value="2" tone="danger"/><Insight label="Positionen offen" value="1" tone="warning"/></div><div className="mt-4 space-y-2"><Task text="Referenzliste hochladen" urgent/><Task text="Ortsbesichtigung bestätigen" urgent/><Task text="Los 1 kalkulieren"/></div></div></div></div></section>
  <section className="container-shell py-16"><div className="grid gap-5 md:grid-cols-3"><Feature icon={Upload} title="Unterlagen bündeln" text="PDF, Office-Dateien, XML, CSV und ZIP werden projektbezogen erfasst; nicht auslesbare Dokumente bleiben sichtbar."/><Feature icon={FileSearch} title="Belegt analysieren" text="Fristen, Lose, Nachweise, Risiken und Positionen erhalten Fundstellen und einen Prüfstatus."/><Feature icon={ShieldCheck} title="Kontrolliert freigeben" text="Checkliste, Kalkulation und Freigabeprotokoll helfen; automatischer Angebotsversand ist ausgeschlossen."/></div></section>
  <section className="bg-brand-900 py-16 text-white"><div className="container-shell"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-widest text-brand-100">Der Ablauf</p><h2 className="mt-3 text-3xl font-semibold">Von den Unterlagen zur belastbaren internen Entscheidung</h2></div><div className="mt-10 grid gap-4 md:grid-cols-5">{['Upload oder E-Mail', 'Analyse prüfen', 'Go/No-Go entscheiden', 'Kalkulation vorbereiten', 'Manuell einreichen'].map((text, index) => <div key={text} className="rounded-xl border border-white/10 bg-white/5 p-4"><span className="text-sm text-brand-100">0{index + 1}</span><p className="mt-3 font-medium">{text}</p></div>)}</div></div></section>
</>

const Insight = ({ label, value, tone }: { label: string; value: string; tone: 'success' | 'warning' | 'danger' }) => <div className="rounded-lg border border-slate-100 p-3"><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 text-sm font-semibold ${tone === 'success' ? 'text-emerald-700' : tone === 'danger' ? 'text-red-700' : 'text-amber-700'}`}>{value}</p></div>
const Task = ({ text, urgent }: { text: string; urgent?: boolean }) => <div className="flex items-center gap-2 rounded-lg border border-slate-100 px-3 py-2 text-sm"><span className={`h-2 w-2 rounded-full ${urgent ? 'bg-red-500' : 'bg-brand-500'}`}/>{text}</div>
const Feature = ({ icon: Icon, title, text }: { icon: typeof Upload; title: string; text: string }) => <Card><Icon className="h-7 w-7 text-brand-600"/><h3 className="mt-4 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></Card>

export const FeaturesPage = () => <div className="container-shell py-14"><div className="max-w-3xl"><Badge tone="info">Funktionsumfang des MVP</Badge><h1 className="mt-4 text-4xl font-semibold">Ein klarer Prüfworkflow statt einer undurchsichtigen KI-Antwort</h1><p className="mt-5 text-lg text-slate-600">TenderWerk verbindet Dokumentanalyse mit Unternehmensprofil, Entscheidungslogik, Kalkulationsvorbereitung und Freigabe.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{[
  [FileSearch, 'Fundstellenbezogene Analyse', 'Jeder kritische Eintrag zeigt Dokument, Stelle, Ausschnitt, Konfidenz und Bestätigungsstatus.'],
  [Layers3, 'Lose und Positionen', 'Passung wird pro Los bewertet; LV-Positionen können kalkuliert und bestätigt werden.'],
  [Timer, 'Fristen und Nachweise', 'Kritische Termine, Muss-Nachweise, offene Formblätter und Konflikte werden priorisiert.'],
  [WalletCards, 'Kalkulationsvorbereitung', 'Deterministische Formeln für Personal, Material, Zuschläge, Risiko und Marge.'],
  [CheckCircle2, 'Go-/No-Go-Modell', 'Der Score folgt transparenten Dimensionen und harten, belegpflichtigen Stopps.'],
  [ShieldCheck, 'Freigabe-Gate', 'Keine automatische Abgabe: Prüfer bestätigen Originalunterlagen und offene Risiken.']
].map(([icon, title, text]) => <Feature key={String(title)} icon={icon as typeof Upload} title={String(title)} text={String(text)}/>)}</div><div className="card mt-10 border-amber-200 bg-amber-50"><h2 className="text-lg font-semibold text-amber-900">Bewusste MVP-Grenzen</h2><p className="mt-2 text-sm leading-6 text-amber-900">OCR für reine Scans, tiefe GAEB-Varianten, Produktsuche, Zahlungsabwicklung und automatische Vergabeportal-Einreichung sind nicht als sichere Vollfunktion behauptet. Scans werden markiert und die Abgabe bleibt manuell.</p></div></div>

export const PricesPage = () => <div className="container-shell py-14"><div className="max-w-3xl"><Badge tone="warning">Preisvalidierung – noch kein Checkout</Badge><h1 className="mt-4 text-4xl font-semibold">Testmodelle für Betriebe mit unterschiedlichem Bedarf</h1><p className="mt-5 text-lg text-slate-600">Diese Preise sind Hypothesen für Kundentests. Im MVP werden Zugänge und Kontingente administrativ gesteuert.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-4">{[
  ['Einzelanalyse Starter', '29–49 €', 'Einfache Unterlagen und begrenztes Dateipaket'],
  ['Einzelanalyse Komplex', '79–99 €', 'ZIP, mehrere Dokumente und LV-Prüfung'],
  ['Kleinbetrieb', 'ab 99 €/Monat', 'Begrenztes Monatskontingent und Export'],
  ['Betrieb Plus', 'bis 499 €/Monat', 'Teamrollen und optionaler E-Mail-Eingang']
].map(([title, price, text]) => <Card key={title}><h2 className="font-semibold">{title}</h2><p className="mt-3 text-3xl font-semibold text-brand-700">{price}</p><p className="mt-4 text-sm text-slate-600">{text}</p><Link className="btn-secondary mt-6 w-full" to="/registrieren">Testzugang anfragen</Link></Card>)}</div></div>

export const SecurityPage = () => <div className="container-shell py-14"><div className="max-w-3xl"><Badge tone="success">Security by Design</Badge><h1 className="mt-4 text-4xl font-semibold">Vertrauliche Unterlagen benötigen klare Grenzen</h1><p className="mt-5 text-lg text-slate-600">Das Produktkonzept setzt auf private Storage-Buckets, Mandantentrennung, serverseitige KI-Schlüssel und menschliche Freigabe.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{['Private Dokumentenspeicherung in Supabase Storage mit RLS und signierten Downloadlinks.', 'Secrets nur serverseitig in Supabase Functions oder Cloudflare Worker Secrets.', 'Analyseergebnisse mit Fundstellen, Konfidenz und Bestätigungspflicht.', 'Kein automatischer Versand oder Upload von Angeboten an Vergabestellen.'].map((item) => <Card key={item}><p className="flex gap-3 text-sm leading-6"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-brand-600"/>{item}</p></Card>)}</div><div className="card mt-10"><h2 className="section-title">Vor Livebetrieb erforderlich</h2><p className="mt-3 text-sm leading-6 text-slate-600">Betreiberangaben, Datenschutzinformation, Auftragsverarbeitung, Hostingregion, KI-Anbieterbedingungen, Preis-/Vertragstexte und etwaige Cookies oder Tracking müssen vor dem kommerziellen Einsatz final geprüft und ausgefüllt werden.</p></div></div>

export const LegalTemplatePage = ({ type }: { type: 'impressum' | 'datenschutz' }) => <div className="container-shell py-14"><div className="mx-auto max-w-3xl"><Badge tone="warning">Vorlage – vor Veröffentlichung ausfüllen und prüfen</Badge><h1 className="mt-4 text-4xl font-semibold">{type === 'impressum' ? 'Impressum' : 'Datenschutzinformation'}</h1><div className="card mt-8 space-y-5 text-sm leading-7 text-slate-700">{type === 'impressum' ? <><p><strong>Betreiber:</strong> &lt;VOLLSTÄNDIGER NAME / UNTERNEHMENSBEZEICHNUNG&gt;</p><p><strong>Anschrift:</strong> &lt;LADUNGSFÄHIGE ANSCHRIFT&gt;</p><p><strong>Kontakt:</strong> &lt;E-MAIL&gt; · &lt;TELEFON&gt;</p><p><strong>Register-/Steuerangaben:</strong> &lt;FALLS ERFORDERLICH&gt;</p></> : <><p>Diese Seite muss vor Livebetrieb den Verantwortlichen, Verarbeitungszwecke, Rechtsgrundlagen, Speicherdauer, Empfänger/Dienstleister, KI-Verarbeitung, Betroffenenrechte und Kontaktangaben enthalten.</p><p><strong>Zu prüfen und zu ergänzen:</strong> Supabase-Region und AV-Vertrag, Cloudflare-Verarbeitung, eingesetzter KI-Anbieter, Auth-E-Mails/SMTP, Upload- und Löschfristen, eventuelle Analyse-/Loggingdienste.</p><p>Im bereitgestellten MVP sind Tracking- und Marketing-Cookies standardmäßig nicht integriert.</p></>}</div></div></div>
